### ISSUE TITLE
Adding new country to prefs is a problem

### ISSUE THREAD

**Issue by sander1** [plexinc-agents/TheMovieDB.bundle#25]
@mmccurdy07 @jam @chriscurtis

https://github.com/plexinc-agents/TheMovieDB.bundle/commit/f22a8b56203058979b1bc15d5c5893f9bc71d8f3#diff-a7f5bee015abcba24763f9e62e01df74R50

~~See also https://github.com/plexinc-agents/TheMovieDB.bundle/issues/24~~

~~15ef17ff35c9da80029fb58a94320a8fa9683747 is not really the solution to this.~~

**Comment by maxGreenblatt** [comment]
@sander1: I added new countries recently and it worked for me. Is this still a problem? I'm closing this, but re-open if I misunderstood the issue.
