### ISSUE TITLE
Missing ratings

### ISSUE THREAD

**Issue by ukdtom** [plexinc-agents/TheMovieDB.bundle#31]
Nothing shown in the logs, but seems like ratings is no longer fetched from themoviedb.org?

**Comment by ukdtom** [comment]
Disregards for now.....Seems like some are getting the ratings.....I need to dig further into this

**Comment by sander1** [comment]
Rating from TMDB is used when there's more than 3 votes: https://github.com/plexinc-agents/TheMovieDB.bundle/blob/master/Contents/Code/__init__.py#L198-L202

**Comment by ukdtom** [comment]
As spock would have said: "It's logical" ;-)

Thanks Sander
