### ISSUE TITLE
TMDB agent should pick poster with the highest rating as default

### ISSUE THREAD

**Issue by OttoKerner** [plexinc-agents/TheMovieDB.bundle#34]
On the movie Database, posters are rated. Usually the 'cleanest' posters are rated highest. 
If the agent would pick the highest rated as default poster instead of the first one, most users would benefit.

Forum topic with examples 
https://forums.plex.tv/discussion/176034/tmdb-poster-order

**Comment by sandman4sure** [comment]
https://www.themoviedb.org/talk/5554c3aa9251416dd6002bcf
Primary isn't supported by the API yet

**Comment by maxGreenblatt** [comment]
We do sort posters by rating now: https://github.com/plexinc-agents/TheMovieDB.bundle/blob/master/Contents/Code/__init__.py#L424
