### ISSUE TITLE
API key has been suspended

### ISSUE THREAD

**Issue by chse** [plexinc-agents/TheMovieDB.bundle#46]
The API_KEY hard-coded into __init__.py has been suspended.  Just try `http://api.tmdb.org/3/configuration?api_key=a3dc111e66105f6387e99393813ae4d5`

Suggested solution:
Contact TheMovieDB.org to apply for a new API key.

**Comment by ukdtom** [comment]
Plex is looking into this, and thanks for the report

**Comment by sander1** [comment]
The code in this repository is no longer the code shipped with and used by Plex Media Server. Plex has it's own caching servers between The Movie Database and their software. Everything you see here is outdated.
